sources:
  - name: Authzed-gRPC
    handler:
      grpc:
        endpoint: localhost:50051
        useHTTPS : false
        useReflection: true
        metaData:
          Authorization: 'somerandomkey'
        protoFilePath:
          file: ./proto/authzed/api/v1/permission_service.proto
          load:
            includeDirs:
              - ./proto
    transforms:
      - namingConvention:
          fieldNames: camelCase   