sources:
  - name: Authzed-OpenAPI
    handler:
      openapi:
        source: https://raw.githubusercontent.com/authzed/authzed-go/main/proto/apidocs.swagger.json
  - name: Authzed-gRPC
    handler:
      grpc:
        endpoint: grpc.authzed.com:443
        useHTTPS : true
        packageName: authzed.api.v1
        metaData:
          Authorization: 'Bearer {env.AUTHZED_CLIENT_TOKEN}'
        protoFilePath:
          file: ./proto/authzed/api/v1/permission_service.proto
          load:
            includeDirs:
              - ./proto
    transforms:
      - namingConvention:
          fieldNames: camelCase   